# Generated by Django 5.0.6 on 2024-07-11 17:30

import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid6.uuid7, primary_key=True, serialize=False)),
                ('text', models.TextField(max_length=3000)),
                ('title', models.TextField(max_length=80)),
                ('like_count', models.PositiveBigIntegerField(default=0)),
                ('status', models.CharField(choices=[('pendaftaran', 'Pendaftaran'), ('pemeriksaan_berkas', 'Pemeriksaan Berkas'), ('bayar_penjar_perkara', 'Bayar Panjar Perkara'), ('panggilan_sidang', 'Panggilan Sidang'), ('proses_persidangan', 'Proses Persidangan'), ('putusan', 'Putusan')], default='pendaftaran', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
