# Generated by Django 5.0.6 on 2024-07-11 16:22

import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_lawexpertsignup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lawexpertsignup',
            old_name='lawyer_certificate',
            new_name='law_certificate',
        ),
        migrations.AlterField(
            model_name='lawexpertsignup',
            name='id',
            field=models.UUIDField(default=uuid6.uuid7, primary_key=True, serialize=False),
        ),
    ]
